# Generated by Django 3.2.10 on 2022-01-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produty',
            new_name='Produkty',
        ),
    ]
