# Generated by Django 3.2.10 on 2022-01-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0003_auto_20220111_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='gatunek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.gatunki'),
        ),
    ]
