# Generated by Django 3.2.10 on 2022-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0005_auto_20220111_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gatunek', models.CharField(max_length=100)),
                ('kategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='gatunek',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='Gatunki',
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
        migrations.DeleteModel(
            name='Produkty',
        ),
    ]
