# Generated by Django 3.2.10 on 2022-01-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0006_auto_20220118_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkt', to='Produkty.kategoria'),
        ),
    ]
