# Generated by Django 3.2.10 on 2022-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0007_auto_20220118_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(default=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='slug',
            field=models.SlugField(default=True, max_length=255, unique=True),
        ),
    ]
