# Generated by Django 3.2.10 on 2022-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0008_auto_20220118_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='slug',
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kategoria',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
    ]
