# Generated by Django 3.2.10 on 2022-01-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0010_auto_20220118_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zdjecia',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
