# Generated by Django 3.2.10 on 2022-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0011_produkt_zdjecia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='zdjecia',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
