# Generated by Django 3.2.9 on 2022-01-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=11)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
